FROM bash

ARG ENV_SPECIFED_IN_SHELL_PASSED_VIA_ARG_IN_COMPOSE 

ENV ENV_SPECIFED_IN_DOCKERFILE_AS_CONSTANT 'yes'
ENV ENV_SPECIFED_IN_DOCKERFILE_AS_ENV_VAR $ENV_SPECIFED_IN_DOCKERFILE_AS_ENV_VAR
ENV ENV_SPECIFED_IN_SHELL_PASSED_VIA_ARG_IN_COMPOSE $ENV_SPECIFED_IN_SHELL_PASSED_VIA_ARG_IN_COMPOSE

WORKDIR /app

COPY . .

RUN ./script.sh

CMD ["bash", "./script.sh"]